# Generated by Django 6.0.3 on 2026-03-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PackingMachine',
            fields=[
                ('material_code', models.CharField(editable=False, help_text='唯一的物料编码', max_length=20, primary_key=True, serialize=False, verbose_name='物料编码')),
                ('drawing_no', models.CharField(help_text='示例图编号', max_length=20, verbose_name='图号')),
                ('standards', models.CharField(help_text='M5*30', max_length=20, verbose_name='规格')),
                ('machine_name', models.CharField(help_text='零件的中文名称', max_length=100, verbose_name='零件名称')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='单位:元', max_digits=15, null=True, verbose_name='价格')),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='单位:元', max_digits=15, null=True, verbose_name='卖价')),
                ('image', models.ImageField(blank=True, help_text='零件图片文件', null=True, upload_to='machines/', verbose_name='图片')),
                ('model_type', models.CharField(choices=[('XQD-19气动打包机', 'XQD-19气动打包机'), ('XQD-25气动打包机', 'XQD-25气动打包机'), ('GSC32气动打包机', 'GSC32气动打包机'), ('GSC32气动卡扣机', 'GSC32气动卡扣机'), ('KCL气动打包机', 'KCL气动打包机'), ('KCL气动卡扣机', 'KCL气动卡扣机'), ('FTL32气动打包机', 'FTL32气动打包机'), ('FTL32气动卡扣机', 'FTL32气动卡扣机')], default='XQD-19', max_length=20, verbose_name='所属机型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '气动打包机物料清单',
                'ordering': ['material_code'],
            },
        ),
    ]
