# Generated by Django 6.0.3 on 2026-04-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingmachine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='packingmachine',
            name='material_code',
            field=models.CharField(help_text='唯一的物料编码', max_length=20, primary_key=True, serialize=False, verbose_name='物料编码'),
        ),
    ]
